### ISSUE TITLE
Scratch editor shows no prompt after finishing loading with the prepackaged cljs4excel

### ISSUE THREAD

**Issue by yubrshen** [cfelde/cljs4excel#14]
I followed the instruction at https://www.cljs4excel.com/
After inserting app, I did see the text "cljs4excel" (where "OfficeApp2" is in the illustration at the web page: https://www.cljs4excel.com/)
 at the right panel next to my spreadsheet, underneath the text, in the same panel, I saw blank white area, but not prompt at all, and I could not enter any text there. 

Please advise how to investigate the problem. 

I'm on Windows 7 with Excel 2013.

Thanks,

**Comment by cfelde** [comment]
Hi,

Thanks for sharing the details. Sounds like it's failing during loading of
the app.

I don't actually have access to 2013 myself, so I'll need to look into that
first if I'm going to have any chance of replicating.

Potentially the only way to get more insight into why it doesn't load is to
create a Visual Studio project and debug it from there. Alternatively set
it up on a local web server (using the included python script) and see
which files it loads, but not sure it will give too much info.

**Comment by yubrshen** [comment]
Hi, 

I tired with local installation. Then I found one clue. 

When loading, it complainted:

"To help protect your security, your web browser has restricted this file from showing active content that could access your computer. Click here for options..."

I clicked the error message prompt to enable the access. initially, it still didn't work with the blank at the scratch editor error. 

Then I saved the new file, and re-open the saved file, the second time it prompts with the error message of security warning, I clicked and enabled starting ActvieX access, then with a few carriage returns, then I saw message of 
"Loading cljs4excel..
cljs4excel ready.."

BANG! It worked. 

My understanding of the working mechanism is limited. So you might make more sense of what went 
on. I'm not sure which helped to make it work.
- local installation or 
- saving the file with the application inserted or 
- merely patience of waiting after enable the ActiveX content?

Thanks!

**Comment by yubrshen** [comment]
Hi Christian,

I raised some questions or comments at the wiki. With your help, we may be
able to build up more user documentation.

Thanks in advance,

Yu

**Comment by cfelde** [comment]
Glad you got it working, and happy to see you adding to the wiki! :)

Would be great if maybe you could do a few comments + screenshots on the steps you did for Excel 2013 on the wiki?

**Comment by yubrshen** [comment]
Add the problem description, and solution in the wiki. But I could not figure how to add screen shot yet.

**Comment by cfelde** [comment]
Looks good, if you email me the screenshots I'll be happy to add them in.
Just send them over to cfelde [at] cfelde [dot] com, thanks.

Best regards
Christian Felde - cfelde@cfelde.com
