### ISSUE TITLE
Google Docs

### ISSUE THREAD

**Issue by reilly3000** [cfelde/cljs4excel#2]
I love this project! I'm trying to decide right now about an OS choice for a bunch of people and projects. If I could run something like this in Google Sheets with Apps Script I would be able to use ChromeOS or a *nix universally. But Excel on Windows has SO MUCH GOOD STUFF. Is there a path to compose with Excel but still use Google Docs as a backend?

**Comment by cfelde** [comment]
I haven't really looked much at Google Apps Script, but if it exposes a similar level of functionality, and it allows you to load the ClojureScript REPL content you need, I'd guess it could work.

But on the Excel side: These web based addins should also work in their online and iPad versions. Similarly it's a future feature for Office for Mac as well I've heard. Check the table in this link: https://msdn.microsoft.com/EN-US/library/office/dn833104.aspx
