### ISSUE TITLE
403 When trying to download.

### ISSUE THREAD

**Issue by escherize** [cfelde/cljs4excel#3]
Hi!

Awesome project, can't wait to try.

I'm getting a 403 at: [https://www.cljs4excel.com/app/latest](https://www.cljs4excel.com/app/latest)

Cheers!

**Comment by cfelde** [comment]
Hi,

Yes, need to improve this a bit as a directory listing is disallowed. For
now: Go directly to https://www.cljs4excel.com and follow the instructions
there.

Hope that helps, if not please let me know?
- Christian

**Comment by cfelde** [comment]
I've clarified the installation steps in README.md, so hope that makes it simpler.
